import type { Metadata } from 'next';
import './globals.css';
import Header from '../components/header';
import Footer from '../components/footer';
import ProjectContainer from '../components/projectContainer';
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-gradient-to-t from-orange-200 via-orange-100 to-orange-100 '>
        <ProjectContainer>
          <Header />
          <Toaster position="bottom-center" />
          {children}
          <Footer />
        </ProjectContainer>
      </body>
    </html>
  );
}
